// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdeaCreated {
    /// Indexed addr
    #[prost(string, tag="1")]
    pub idea: ::prost::alloc::string::String,
    /// Indexed addr
    #[prost(string, tag="2")]
    pub creator: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub contributor_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub contribution: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="6")]
    pub created_at_block: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IdeaCreatedEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<IdeaCreated>,
}
// @@protoc_insertion_point(module)
