// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolutionContribution {
    /// Indexed addr
    #[prost(string, tag="1")]
    pub addr: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub position_index: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub total_shares: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub total_tokens: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolutionContributionEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<SolutionContribution>,
}
// @@protoc_insertion_point(module)
