// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolutionCreated {
    #[prost(string, tag="1")]
    pub solution: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub creator: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub idea: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub funding_token: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub stake: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub goal: ::prost::alloc::string::String,
    /// TODO: uint256 as uint64 (Unix timestamp)?
    #[prost(string, tag="7")]
    pub deadline: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub contributor_fee: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="9")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SolutionCreatedEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<SolutionCreated>,
}
// @@protoc_insertion_point(module)
